### ISSUE TITLE
[bug] Mempool indexes again from scratch on every restart

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/mempool-wrapper#10]
This should be saved in MariaDB index and only index any blocks that it did not know about since last running

**Comment by cryptodread** [comment]
looking at including this in the v2.4.0.1 release

**Comment by cryptodread** [comment]
this is ready to test in the 2.4.0.1 on alpha

**Comment by kn0wmad** [comment]
Unable to repro at this time, will try on additional test rigs

**Comment by cryptodread** [comment]
Closing, fixed in v2.4.0.1.
