### ISSUE TITLE
[feat]: Update to v2.5.0

### ISSUE THREAD

**Issue by heredia21** [Start9Labs/mempool-wrapper#20]
### Prerequisites

- [X] I have searched for existing issues that already suggest this feature.

### Describe the Feature Request

Requesting to update mempool: https://twitter.com/mempool/status/1640715797097246723

https://github.com/mempool/mempool/releases/tag/v2.5.0

### Describe the Use Case

N/A

**Comment by islandbitcoin** [comment]
Closed as duplicate of https://github.com/Start9Labs/mempool-wrapper/issues/16
