### ISSUE TITLE
"Miner" tab does not work with Proxy dependency

### ISSUE THREAD

**Issue by MattDHill** [Start9Labs/mempool-wrapper#3]
When using Bitcoin Proxy as the internal dependency, the "Miner" does not populate at all. There are no errors in the Mempool logs or the Proxy logs. Switching to use Core directly resolves the issue.

To reproduce, simply make Proxy the dependency, launch Mempool, and open the Miner tab.

**Comment by ProofOfKeags** [comment]
Wild. My best guess is that this is actually a bug with Proxy and that it isn't rendering the coinbase input properly, which is where I think this inference is made. We should verify exactly how it is being assessed from within mempool and if it's an issue with the rendering of some RPC call we can transfer the issue.

**Comment by MattDHill** [comment]
Add `getnetworkhashps` to autoconfig for Proxy solves

**Comment by cryptodread** [comment]
fix up on beta and ready for test

**Comment by cryptodread** [comment]
resolved in v4.2.0
